name: CICD

on:
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      DIR_TITLE: build
    steps:
      - name: build
        env:
          MY_VAR: Hi! My name is,
          FIRST_NAME: Slim
          LAST_NAME: Shady
        run:  mkdir -p $DIR_TITLE | touch ./$DIR_TITLE/info.txt && echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME > ./$DIR_TITLE/info.txt
      - name: test
        run: if [ -f ./$DIR_TITLE/info.txt ]; then echo "File info.txt exists" && cat ./$DIR_TITLE/info.txt; else echo "File info.txt doesn't exits"; fi

