# This is a basic workflow to help you get started with Actions

name: CICD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: build
        run: echo "yobana rot!!!" > test.txt
      - name: test
        run: cat test.txt
