# This is a basic workflow to help you get started with Actions

name: CICD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: mkdir build |
          echo "Privet!" > ./build/info.txt
      - name: test
        run: echo "Testung" |
          if [ -f ./build/info.txt ]; then echo "File info.txt exists"; else echo "File info.txt doesn't exits"; fi

